apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: linker-helm-chart
  namespace: flux-system
spec:
  interval: 1m0s
  # If the repo is Public, use HTTPS. If Private, you'll need SSH + a secret.
  url: https://github.com/DrdmRandom/helm-chart.git
  ref:
    branch: main
