apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linker
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: linker
  chart:
    spec:
      # IMPORTANT: If your Chart.yaml is in a subfolder (e.g., charts/linker),
      # change this to that path. If it's at the root of the repo, keep it as ./
      chart: ./linker
      sourceRef:
        kind: GitRepository
        name: linker-helm-chart
        namespace: flux-system
      interval: 1m
  # These values override your values.yaml
  values:
    image:
      repository: api-registry.cihuyproject.my.id/linker
      tag: latest
    imagePullSecrets:
      - name: regsitry-credentials
    
