apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linker
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: linker
  chart:
    spec:
      chart: ./linker
      sourceRef:
        kind: GitRepository
        name: linker-helm-chart
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: api-registry.cihuyproject.my.id/linker
      tag: latest
    imagePullSecrets:
      - name: registry-credentials
    ingress:
      enabled: true
      className: nginx
      annotations: {}
      hosts:
        - host: linker.cihuyproject.my.id
          paths:
            - path: /
              pathType: Prefix
    publicBaseUrl: "https://linker.cihuyproject.my.id"
    google:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: google-oauth-credentials
      valuesKey: clientId
      targetPath: google.clientId
    - kind: Secret
      name: google-oauth-credentials
      valuesKey: clientSecret
      targetPath: google.clientSecret
